In [1]:
import numpy as np

In [2]:
%config Completer.use_jedi = False

In [3]:
np.set_printoptions(threshold=sys.maxsize)

NameError: name 'sys' is not defined

In [2]:
x1 = np.array([[1,0,0,1],
               [1,0,0,1],
               [1,0,0,1],
               [1,0,0,1]])

x2 = np.array([[0,1,1,0],
               [0,1,1,0],
               [0,1,1,0],
               [0,1,1,0]])

x3 = np.array([[0,0,1,0],
               [0,0,1,0],
               [0,0,1,0],
               [0,0,1,0]])

y1 = np.array([[9,8,8,9],
               [9,8,8,9],
               [9,8,8,9],
               [9,8,8,9]])

y2 = np.array([[8,9,9,8],
               [8,9,9,8],
               [8,9,9,8],
               [8,9,9,8]])

y3 = np.array([[8,8,9,8],
               [8,8,9,8],
               [8,8,9,8],
               [8,8,9,8]])

In [ ]:
asd = np.zeros((2,4,4))
x = x.flatten()
print(x.shape)

asd = 

In [3]:
x = np.zeros((3,4,4))

x[0] = x1
x[1] = x2
x[2] = x3

x

array([[[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.]],

       [[0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]]])

In [6]:
xbis = np.moveaxis(x,0,2)
#xbis=np.rollaxis(x,0,3)
xbis.shape

(4, 4, 3)

In [13]:
xbis[:,:,:]

(4, 4, 3)

In [4]:
y = np.zeros((3,4,4))

y[0] = y1
y[1] = y2
y[2] = y3

y

array([[[9., 8., 8., 9.],
        [9., 8., 8., 9.],
        [9., 8., 8., 9.],
        [9., 8., 8., 9.]],

       [[8., 9., 9., 8.],
        [8., 9., 9., 8.],
        [8., 9., 9., 8.],
        [8., 9., 9., 8.]],

       [[8., 8., 9., 8.],
        [8., 8., 9., 8.],
        [8., 8., 9., 8.],
        [8., 8., 9., 8.]]])

In [5]:
idx = np.arange(3)
np.random.seed(0)
np.random.shuffle(idx)

x = x[idx,:,:]
y = y[idx,:,:]

In [6]:
x

array([[[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]],

       [[0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.]],

       [[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 0., 0., 1.]]])

In [7]:
y

array([[[8., 8., 9., 8.],
        [8., 8., 9., 8.],
        [8., 8., 9., 8.],
        [8., 8., 9., 8.]],

       [[8., 9., 9., 8.],
        [8., 9., 9., 8.],
        [8., 9., 9., 8.],
        [8., 9., 9., 8.]],

       [[9., 8., 8., 9.],
        [9., 8., 8., 9.],
        [9., 8., 8., 9.],
        [9., 8., 8., 9.]]])

In [8]:
k = np.arange(10)
np.random.seed(0)
np.random.shuffle(k)
print(k)

[2 8 4 9 1 6 7 3 0 5]
