In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.load("/opt/datos/dataset/gfs/X_shuffle_4-6-9.npy")

In [3]:
X[0,0,0:100,0:100]

array([[5890.62988281, 5890.18994141, 5889.75      , ..., 5849.18994141,
        5849.58984375, 5850.10986328],
       [5891.56982422, 5891.14990234, 5890.75      , ..., 5846.79003906,
        5847.04980469, 5847.35009766],
       [5892.36962891, 5892.00976562, 5891.64990234, ..., 5844.86962891,
        5844.48974609, 5844.83007812],
       ...,
       [5366.10986328, 5366.04980469, 5365.96972656, ..., 5572.02978516,
        5572.37011719, 5572.64990234],
       [5357.72998047, 5357.79003906, 5357.88964844, ..., 5564.25      ,
        5564.68994141, 5565.04980469],
       [5348.48974609, 5348.79003906, 5349.12988281, ..., 5556.20996094,
        5556.79003906, 5557.27001953]])

In [9]:
X = X.flatten()
print(X.shape)

(1244596776,)


In [11]:
for i,x in enumerate(X):
    X[i] = round(x,2)

In [12]:
X = np.reshape(X,(19288,3,137,157))
print(X.shape)

(19288, 3, 137, 157)


In [13]:
X[0,0,0:100,0:100]

array([[5890.63, 5890.19, 5889.75, ..., 5849.19, 5849.59, 5850.11],
       [5891.57, 5891.15, 5890.75, ..., 5846.79, 5847.05, 5847.35],
       [5892.37, 5892.01, 5891.65, ..., 5844.87, 5844.49, 5844.83],
       ...,
       [5366.11, 5366.05, 5365.97, ..., 5572.03, 5572.37, 5572.65],
       [5357.73, 5357.79, 5357.89, ..., 5564.25, 5564.69, 5565.05],
       [5348.49, 5348.79, 5349.13, ..., 5556.21, 5556.79, 5557.27]])

In [14]:
np.save("/opt/datos/dataset/gfs/X_shuffle_rounded.npy", X)

In [2]:
Y = np.load("/opt/datos/dataset/gfs/Y_shuffle.npy")

In [3]:
Y[0,0:10,0:10]

array([[0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 4., 6., 4.],
       [0., 0., 0., ..., 4., 6., 4.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
Y[2000:2900]

array([ 4.,  4.,  0.,  2.,  0.,  0.,  0.,  0.,  1.,  0.,  3.,  3.,  1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,
        2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10., 14.,
        2.,  0.,  2.,  0.,  0.,  2.,  4.,  6.,  6.,  2.,  2.,  0.,  0.,
        1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [4]:
print(Y.shape)
Y = Y.flatten()
print(Y.shape)

(19288, 137, 157)
(414865592,)


In [ ]:
for j,y in enumerate(Y):
    Y[j] = round(y,2)
    if((j%1000000)==0):
        print(i)

In [ ]:
Y = np.reshape(Y,(19288,3,137,157))
print(Y.shape)

In [ ]:
Y[0,0:100,0:100]